### PR TITLE
Buy/Selling regex cleanup

### PR DESCRIPTION
**Pull request by tfemby**
The regex formerly was made up of things I came across and appended to over time. I cleaned up the regex by combining some of the groups and adding a couple of new terms.

New Terms:
- Masori items have been added to the 'sets' group
- Added 'Zaryte' as a part of the 'crossbow' group '(arma(dyl)?|zaryte)?( c(ross|( )?bow)?)?'

Cleanup:
- 'ancestral set' is now part of the 'masori|torva|bandos|armadyl|ancestral' group
- 'inquisitors' has been also added to the above group
- 'dwh' now matches against 'd(ragon)? (claws(s)?|w(ar)?h(ammer)?'
- 'dhl' and 'dhcb' now match against 'd(ragon( )?)?h(unter)?( )?(c(ross| )+?b(ow)?|l(ance)?)'
- Removed capitalization on the words, 'buying' and 'looking'
- Removed 'big chance to win( a)?) (t(wisted)?( )?bow' as I haven't been able to see this in game in a long while
- 'kodai wand' is now 'kodai( wand)?' as it's not impossible to imagine just 'kodai' being used

I also removed the trailing '.*' of the regex as I saw that it was filtering out messages such as:
- Loooking for help
- Looking for a litlle help

The new added terms have been able to filter out:
- Buy zaryte crossbow 650m / buy masori set + pegs 500m

And the following continue to be filtered out:
- Buy Kodai 195m and dragon claws 145m
- Buying ancestral set 520m.

My goal of this commit is to hopefully make this monster regex a little easier to work with in the future.

### CODE REVIEW

**Comment by tfemby** [comment]
I just looked through some older commits (namely https://github.com/IamReallyOverrated/Runelite_ChatFilter/pull/8 ) and think I can probably also add in the couple of missing words still not filtered in that issue.

**Comment by tfemby** [comment]
Upon further testing, don't merge this yet.

**Comment by tfemby** [comment]
This should now work okay. Give it a look and try whenever you have time :)

**Comment by Psicoses** [comment]
I'm grateful someone was willing to work this regex. This looks like an overall improvement, I'm going to add it to the untested branch for a few days to test it.

Thanks!

**Comment by tfemby** [comment]
Just give me an @ and I'm happy to tinker with it.

**Pull request merged**
